name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select option"
        required: true
        type: choice
        options:
          - a
          - b
          - c

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print selected option
        run: echo "Selected option is ${{ github.event.inputs.environment }}"